<a href="https://colab.research.google.com/github/ptrciabnquit/Linear-Algebra_2nd-Sem/blob/main/Assignment9_Baniquit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Plotting Vector using NumPy and MatPlotLib

In this laboratory we will be discussing the basics of numerical and scientific programming by working with Vectors using NumPy and MatPlotLib.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the libraries in Python for numerical and scientific programming.
2. Visualize vectors through Python programming.
3. Perform simple vector operations through code.

## **NumPy**

#  ADD HERE DESCRIPTION

## ***Representing Vectors***

Now that you know how to represent vectors using their component and matrix form we can now hard-code them in Python. Let's say that you have the vectors:

$$ A = 2\hat{x} + 1\hat{y} \\
B = 6\hat{x} + 4\hat{y}\\
C = 2ax + 1ay - 4az \\
D = 8\hat{i} - 1\hat{j} + 2\hat{k}$$

In which it's matrix equivalent is:

$$ A = \begin{bmatrix} 2 \\ 1\end{bmatrix} , B = \begin{bmatrix} 6 \\ 4\end{bmatrix} , C = \begin{bmatrix} 2 \\ 1 \\  4 \end{bmatrix}, D = \begin{bmatrix} 8 \\ -1 \\ 2\end{bmatrix}
$$
$$ A = \begin{bmatrix} 4 & 1\end{bmatrix} , B = \begin{bmatrix} 6 & 4\end{bmatrix} , C = \begin{bmatrix} 2 & 1 & -4\end{bmatrix} , D = \begin{bmatrix} 8 & -1 & 2\end{bmatrix} 
$$

We can then start doing numpy code with this by:

In [1]:
## Importing necessary libraries
import numpy as np ## 'np' here is short-hand name of the library (numpy) or a nickname.

In [57]:
P = np.array([0, 2])
A = np.array([-1, 2])
T = np.array([
              [5],
              [5],
              [5]
])
Y = np.array ([[-2],
              [0],
              [-3]])
print('Vector P is ', P)
print('Vector A is ', A)
print('Vector T is ', T)
print('Vector Y is ', Y)

Vector P is  [0 2]
Vector A is  [-1  2]
Vector T is  [[5]
 [5]
 [5]]
Vector Y is  [[-2]
 [ 0]
 [-3]]


## ***Describing Vectors in NumPy***

# ADD DESCRIPTION HERE

In [56]:
### Checking shapes
### Shapes tells us how many elements are there on each row and column

P.shape
A = np.array([2, 1, -4, 2, -1.5, 3])
A.shape
T.shape

(3, 1)

In [55]:
### Checking size
### Array/Vector sizes tells us many total number of elements are there in the vector

Y.size

3

In [54]:
### Checking dimensions
### The dimensions or rank of a vector tells us how many dimensions are there for the vector.

T.ndim

2

Good job! ✅ We are done checking shapes, sizes, and dimensions the next step is to explore performing operations with these vectors

### **ADDITION**

# **ADD DESCRIPTION HERE ABOUT ADDITION RULE IN VECTORS**

For instance, adding vector $P$ and vector $B$ we will have a resulting vector:

$$R = 10\hat{x} -3\hat{y} \\ \\or \\ \\ R = \begin{bmatrix} 10 \\ -3\end{bmatrix} $$

Creating that in NumPy in various ways:

In [53]:
R = np.add(P, A) ## this is the functional method usisng the numpy library
O = np.add(T, Y)

In [58]:
R = P + A   ## this is the explicit method, since Python does a value-reference so it can 
            ## know that these variables would need to do array operations.
R

array([-1,  4])

In [71]:
pos1 = np.array([1,0,1])
pos2 = np.array([1,2,3])
pos3 = np.array([24,22,13])
pos4 = np.array([2,4,2])
#R = pos1 + pos2 + pos3 + pos4
#R = np.multiply(pos3, pos4)
R = pos3 / pos4
R

array([12. ,  5.5,  6.5])

##### Try for yourself!

Try to implement subtraction, multiplication, and division with vectors $V$ and $K$!

In [74]:
### Try out you code here! 

V = np.array([12, 28, 20])
K = np.array([2, 4, 6])

R = np.divide(V,K)
R

array([6.        , 7.        , 3.33333333])

In [75]:
R = V - K 
R

array([10, 24, 14])

In [76]:
R = np.multiply(V,K)
R

array([ 24, 112, 120])