<a href="https://colab.research.google.com/github/ptrciabnquit/Linear-Algebra_2nd-Sem/blob/main/Assignment_4_Matrix%20Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE

Laboratory 4: Matrix Operations

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


### Transposition



In [ ]:
P = np.array([
    [1, 2, 3],
    [5, 2, 3],
    [0, 3, 1]
])
P


array([[1, 2, 3],
       [5, 2, 3],
       [0, 3, 1]])

In [ ]:
PT1 = np.transpose(P)
PT1

array([[1, 5, 0],
       [2, 2, 3],
       [3, 3, 1]])

In [ ]:
PT2 = P.T
PT2

array([[1, 5, 0],
       [2, 2, 3],
       [3, 3, 1]])

In [ ]:
np.array_equiv(PT1, PT2)

True

In [ ]:
B = np.array([
    [1, 5, -1, -2],
    [2, 1, 3, 8]
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

### Dot Product / Inner Product

In [ ]:
Y = np.array([
    [2,2],
    [0,2]
])
L = np.array([
    [3,2,3],
    [1,2,2]
])

In [ ]:
np.dot(Y,L)

array([[ 8,  8, 10],
       [ 2,  4,  4]])

In [ ]:
np.array_equiv(Y,L)

False

In [ ]:
Y.dot(Y)

array([[4, 8],
       [0, 4]])

In [ ]:
Y @ L

array([[ 8,  8, 10],
       [ 2,  4,  4]])

In [ ]:
np.matmul(Y,L)

array([[ 8,  8, 10],
       [ 2,  4,  4]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$C = \begin{bmatrix}0&1&2&4\\2&5&2&2\\0&1&5&6\end{bmatrix}, 
D = \begin{bmatrix}1&1&0\\3&3&0\\2&5&8\end{bmatrix}, 
O = \begin{bmatrix}2&0&4&5\\1&5&2&5\end{bmatrix}$$

So in this case $A$ has a shape of $(3,4)$, $B$ has a shape of $(3,4)$ and $C$ has a shape of $(2,4)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
C = np.array([
    [0, 1, 2, 4],
    [2, 5, 2, 2],
    [0, 1, 5, 6]
])
D = np.array([
    [1, 1, 0],
    [3, 3, 0],
    [2, 5, 8]
])
O = np.array([
    [2, 0],
    [1, 5]
])
print(C.shape)
print(D.shape)
print(O.shape)

(3, 4)
(3, 3)
(2, 2)


In [ ]:
D @ C

array([[ 2,  6,  4,  6],
       [ 6, 18, 12, 18],
       [10, 35, 54, 66]])

In [ ]:
D @ C

array([[ 2,  6,  4,  6],
       [ 6, 18, 12, 18],
       [10, 35, 54, 66]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$


In [ ]:
B = np.array([
    [3,2,1],
    [3,2,1],
    [2,0,1]
])
T = np.array([
    [2,1,8],
    [2,1,0],
    [1,4,7]
])
S = np.array([
    [1,1,3],
    [0,0,2],
    [1,2,3]
])

In [ ]:
B.dot(np.zeros(B.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(S.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = T.dot(np.zeros(T.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(B.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [ ]:
np.array_equiv(A.dot(B), A.dot(T))

False

In [ ]:
np.array_equiv(B.dot(S), T.dot(S))

False

In [ ]:
np.array_equiv(S.dot(T),B)

False

### Determinant

In [ ]:
M = np.array([
    [0,9],
    [13,4]
])
np.linalg.det(M)

-117.00000000000003

In [ ]:
Z = np.array([
    [3,3,3],
    [0,1,2],
    [2,5,6]
])
np.linalg.det(Z)

-6.000000000000003

In [ ]:
V = np.array([
    [2,6,2,1],
    [2,4,0,3],
    [5,2,3,2],
    [5,0,1,1]
])
np.linalg.det(V)

131.99999999999997

### Inverse



In [ ]:
N = np.array([
    [2, 2, 9],
    [4, -5, 2],
    [2, 0, 3]
])

np.array(N @ np.linalg.inv(N), dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
P = np.array([
    [2, 8, 2],
    [5, 2, 0],
    [2, 4, 6,]
              
])
Q = np.linalg.inv(P)
Q

array([[-0.06521739,  0.2173913 ,  0.02173913],
       [ 0.16304348, -0.04347826, -0.05434783],
       [-0.08695652, -0.04347826,  0.19565217]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 2.77555756e-17, -5.55111512e-17,  1.00000000e+00]])

## Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.