<a href="https://colab.research.google.com/github/ptrciabnquit/Linear-Algebra_2nd-Sem/blob/main/Assignment_3_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algeb for ChE

## Laboratory 2 : Matrices

### *Objectives:*

At the end of this activity you will be able to:



1.   Be familiar with matrices and their relation to linear equations. 
2.   Perform basic matrix operations.
3.   Program and translate matrix equations and operations using Python.





### **Discussion**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### **Matrices**

#### The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also hand representations of complex equations or multiple inter-related equations from 2-dimentional equation to even hundreds and thousands of them.


Let's say for example you have ***A*** and ***B*** as system of equation:


$$
P = \left\{
    \begin{array}\
        a + y \\ 
        3a - 13y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        a+p+y \\ 
        3a -p -y \\
        -2a + 2p +4y
    \end{array}
\right. $$
















#### We could say that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. We can represent them as matrices as: 

:$$
P=\begin{bmatrix} 1 & 1 \\ 3 & {-13}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -1 & -1 \\ -2 & 2 & 4\end{bmatrix}
$$











### **Declaring Matrices**

The components of a matrix are the entities or values in matrices. Matrices have a category form in which these elements are structured and sorted in rows and columns. Additionally, these categorized elements align to their rows and columns, as with arrays. This can be expressed in the same manner as the expression below. Whereas $A$ is a matrix made up of elements represented by $a_{i,j}$. The number of rows in the matrix is expressed by $i$, meanwhile the number of columns.<br> is denoted by $j$. 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices, let's make a function!
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
P = np.array([
    [2,3],
    [4,4]
])
describe_mat(P)

Matrix:
[[2 3]
 [4 4]]

Shape:	(2, 2)
Rank:	2



In [ ]:
Y = np.array([
    [13, 3],
    [6, 13]
])
describe_mat(Y)


Matrix:
[[13  3]
 [ 6 13]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [2,3],
    [4,4],
    [2,0]
])
describe_mat(B)

Matrix:
[[2 3]
 [4 4]
 [2 0]]

Shape:	(3, 2)
Rank:	2



### **Categorizing Matrices**

A categorizing matrix classifies all situations in the model by assessing whether the anticipated value corresponds to the actual value. The categorization matrix is a commonly used technique for evaluating statistical models; it is also known as a confusion matrix.

#### ***Row and Column Matrices***

The phrases "row and column matrices" and "row and column vectors are commonly interchangeable. Row and Column matrices are prominent in terms of vector and matrix calculations. Moreover, row and column matrices can also depict the rows and columns of broader subspaces. As a result, row matrices would be $i \times 1$, whereas row matrices would be $1 \times j$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
1,6,4,3
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
[3,4,6,8]                     
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 6 4 3]

Shape:	(4,)
Rank:	1

Matrix:
[[3 4 6 8]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix 

colmat = np.array([
  [893],
  [48],
  [333]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(colmat)

Matrix:
[[893]
 [ 48]
 [333]]

Shape:	(3, 1)
Rank:	2



### ***Square Matrices***

When the number of columns and rows are equal, They are known as Square Matrix, also called an n x n matrix.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
[1,13,67],
[2,89,40],
[66,11,22]     
])
non_square_mat = np.array([
[3,5,6],
[8,5,4]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 1 13 67]
 [ 2 89 40]
 [66 11 22]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[3 5 6]
 [8 5 4]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### **According to Element Values**

#### ***Null Matrix***

The null matrix is the additive identity of any matrix; that is why it is advantageous. Also, adding a null matrix to any matrix does not influence the value of the matrix; therefore, recognized as an additive identity. 

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('The Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)
          

The Matrix is Null


#### ***Zero Matrix***

Zero matrices are an additive identity used for matrix addition. It is a matrix that is wholly composed of Zero components

In [ ]:
zero_mat_row = np.zeros((2,1))
zero_mat_sqr = np.zeros((4,3))
zero_mat_rct = np.zeros((5,5))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0.]
 [0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### ***Ones Matrix***

The matrix of one can be any rectangular matrix, similarly to a zero matrix, yet whose elements are all 1s rather than 0s.

In [ ]:
ones_mat_row = np.ones((3,3))
ones_mat_sqr = np.ones((4,6))
ones_mat_rct = np.ones((8,13))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### ***Diagonal Matrix***

A Diagonal Matrix is a square matrix wherein all elements other than the primary diagonal are zeros, and the principal diagonal elements might be zeros or non-zeroes.

In [ ]:
np.array([
   [13,0,0],
   [0,4,0],
   [0,0,18]
])
# a[1,1], a[2,2], a[3,3],... a[n-1,n-1]

array([[13,  0,  0],
       [ 0,  4,  0],
       [ 0,  0, 18]])

In [ ]:
d = np.diag([13,4,8,9])
d.shape[0] == d.shape [1]
d

array([[13,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  8,  0],
       [ 0,  0,  0,  9]])

In [ ]:
d = np.diag([13,4,8,9,100])
d.shape[0] == d.shape [1]
d

array([[ 13,   0,   0,   0,   0],
       [  0,   4,   0,   0,   0],
       [  0,   0,   8,   0,   0],
       [  0,   0,   0,   9,   0],
       [  0,   0,   0,   0, 100]])

### ***Identity Matrix***

A square matrix with the elements of the main diagonal identical with one and the other components equal to zero is known as an identity matrix. In the Python programming language, array objects are detailed lists for vector and matrix calculation.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### **Upper Triangular Matrix:**

In an Upper triangular matrix, all items below the main diagonal are zero in. Additionally, the matrix with zero components above the main diagonal is referred to as a lower triangular matrix.

In [ ]:
np.array([
  [4,3,2,1],
  [0,-1,-2,-3,],
  [5,6,7,8],
  [2,8,7,4]
])

array([[ 4,  3,  2,  1],
       [ 0, -1, -2, -3],
       [ 5,  6,  7,  8],
       [ 2,  8,  7,  4]])

### **Lower Triangular Matrix**

A matrix with no values above the diagonal is defined as a lower triangular matrix.

In [ ]:
np.array([
  [1,2],
  [2,1]
])

array([[1, 2],
       [2, 1]])

### **Matrix Algebra**

Matrix algebra is a notation for simultaneous equations that simplifies their presentation and solution. It may be used to generate a brief explanation of a structural issue and a mathematical structure model.

#### *Addition*

In [ ]:
A = np.array([
    [2,4],
    [5,6],
    [3,2]
])
B = np.array([
    [2,2],
    [3,6],
    [8,8]
])
A+B

array([[ 4,  6],
       [ 8, 12],
       [11, 10]])

In [ ]:
3+A ##Broadcasting
# 3*np.ones(A.shape)+A

array([[5, 7],
       [8, 9],
       [6, 5]])

#### *Subtraction*

In [ ]:
A-B

array([[ 0,  2],
       [ 2,  0],
       [-5, -6]])

In [ ]:
2-B 

array([[ 0,  0],
       [-1, -4],
       [-6, -6]])

#### *Element-Wise Multiplication*

In [ ]:
A*B 
np.multiply(B,A)

array([[ 4,  8],
       [15, 36],
       [24, 16]])

In [ ]:
5*A

array([[10, 20],
       [25, 30],
       [15, 10]])

## **Practice**

1. Given the linear combination below, try to create a corresponding matrix representing it. 



$$\theta = 5x + 3y - z$$

$$
\theta = \begin{bmatrix} 5  &  3 & -1\end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.



$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown, and in a LaTex Markdown.



In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$


$$
G = \left\{
    \begin{array}\
        1 + 7 + 8 \\
        2 + 2 + 2 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations. 



In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

## **Activity**

### ***Task 1***

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which the actions and methods you have done. Present your results in the results ir shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the section showing the description of each matrix you have declared.

In [ ]:
def mat_desc(matrix):
  mat = np.array(matrix)
  xx = False

  iden = np.identity(matrix.shape[0]),
  one = np.ones((matrix.shape[0], matrix.shape[1])),
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))

  is_square = True if matrix.shape[0] == matrix.shape[1] else xx
  is_Empty = True if(matrix.shape[0] == 0 and matrix.shape[1] == 0) else xx
  is_Ind = True if(xx and (iden == mat).all()) else xx
  is_uno = True if((one == mat).all()) else xx
  is_zero = True  if((zero == mat).all()) else xx

  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\nMatrix is Empty: {is_Empty}\nMatrix is an Identity Matrix: {is_Ind}\nMatrix is an ones matrix: {is_uno}\nMatrix is an zeros matrix: {is_zero}\n')


In [ ]:
A = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])
mat_desc(A)

Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Shape:	(3, 3)
Size:	9
Rank:	2
Is Square: True
Matrix is Empty: False
Matrix is an Identity Matrix: False
Matrix is an ones matrix: True
Matrix is an zeros matrix: False



In [ ]:
B = np.array([
    [8, 5, 2],
    [9, 3, 4],
    [1, 0, 1]
])
mat_desc(B)

Matrix:
[[8 5 2]
 [9 3 4]
 [1 0 1]]

Shape:	(3, 3)
Size:	9
Rank:	2
Is Square: True
Matrix is Empty: False
Matrix is an Identity Matrix: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: False



In [ ]:
C = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
mat_desc(C)

Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Size:	9
Rank:	2
Is Square: True
Matrix is Empty: False
Matrix is an Identity Matrix: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: True



In [ ]:
D = np.array([
    [3,6],
    [2,8],
    [1,0]
])
mat_desc(D)

Matrix:
[[3 6]
 [2 8]
 [1 0]]

Shape:	(3, 2)
Size:	6
Rank:	2
Is Square: False
Matrix is Empty: False
Matrix is an Identity Matrix: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: False



In [ ]:
E = np.array([
    [4, 4, 4],
    [4, 4, 4],
    [4, 4, 4]
])
mat_desc(E)

Matrix:
[[4 4 4]
 [4 4 4]
 [4 4 4]]

Shape:	(3, 3)
Size:	9
Rank:	2
Is Square: True
Matrix is Empty: False
Matrix is an Identity Matrix: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: False



### ***Task 2***

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
def mat_operations(mat1,mat2):
  if (len(mat1)<3 and len(mat1[0])<3) or (len(mat2)<3 and len(mat2[0])<3):
    return 'Invalid Matrices. Please try again.'
  
  elif (len(mat1) !=len(mat2)) and (len(mat1[0]) != len(mat2[0])):
    return 'Invalid Matrices. Please try again.'

  else:
    #Viable Matrices
    print('1. Add Matrices (+) ')
    print('2. Subtract Matrices (-) ')
    print('3. Element-Wise Multiplication (*) ')
    print('4. Element-Wise Division (/) ')

    choice = int(input("Please Enter Desired Operation: "))
    result = [[None for _ in range(len(mat1))] for _ in range(len(mat1[0]))]

    if choice==1:
      #Perform Addition
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] + mat2[i][j],3)

      return 'The Sum of the Matrices are '+str(result)

    if choice==2:
      #Perform Subtraction
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] - mat2[i][j],2)

      return 'The Difference of the Matrices are '+str(result)

    if choice==3:
      #Perform Else-Wise Multiplication
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] * mat2[i][j],4)

      return 'The Product of the Matrices are '+str(result)

    if choice==4:
      #Perform Else-Wise Division
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] / mat2[i][j],2)

      return 'The Quotient of the Matrices are '+str(result)

    else:
      return 'No Operation Available. Please try again. '




In [2]:
K = [[10.23,-8, 4.7843],
    [0 ,-2.09, 3.867],
    [0 ,1, 5]]

P = [[2, -9.003, 7],
    [0, 1.454, 3.097],
    [1,4,0]]
    
print(mat_operations(K,P))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 3
The Product of the Matrices are [[20.46, 72.024, 33.4901], [0, -3.0389, 11.9761], [0, 4, 0]]


In [ ]:
Z = [[10,8],
    [0 ,2]]


L = [[2,9],
    [0,1]]
     
print(mat_operations(Z,L))

Matrices are not viable for the operation. Please try again.


In [3]:
D = [[30.432, -15, 5.21],
    [5.25, 2.34, 5.89],
    [2.00, 4.98, -2]]


B = [[-5.55, -3.22, 5],
     [5, 1, 1],
    [2, 2, 2]]
     
print(mat_operations(D,B))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 2
The Difference of the Matrices are [[35.98, -11.78, 0.21], [0.25, 1.34, 4.89], [0.0, 2.98, -4]]


In [4]:
Y = [[30, -16, 5],
    [25, 10, 14],
    [-50, -30, 15]]


K = [[2, 2, 2],
     [2, 2, 2],
    [2, 2, 2]]
     
print(mat_operations(Y,K))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 4
The Quotient of the Matrices are [[15.0, -8.0, 2.5], [12.5, 5.0, 7.0], [-25.0, -15.0, 7.5]]


In [5]:
P = [[30, -16, 5],
    [25, 10, 14],
    [2, 2, 10],
    [-50, -30, 15]]


J = [[2, 2],
     [2, 2, 2],
    [2, 2, 2]]
     
print(mat_operations(P,J))

Invalid Matrices. Please try again.
